camera:
  use_picamera2: true
  resolution: [640, 480]
  framerate: 30
  headless: false

detection:
  mode: "red_dot"       # red_dot | aruco
  red_hsv_lower1: [0, 120, 120]
  red_hsv_upper1: [10, 255, 255]
  red_hsv_lower2: [170, 120, 120]
  red_hsv_upper2: [179, 255, 255]
  min_radius_px: 2
  aruco_dict: "DICT_4X4_50"
  aruco_marker_size_cm: 5.0

hardware:
  servo_x_pin: 17
  servo_y_pin: 27
  button_pin: 22
  pulse_min_us: 500
  pulse_max_us: 2500
  pwm_hz: 50

control:
  center_tolerance_px: 18
  kp_deg_per_px_x: 0.06
  kp_deg_per_px_y: 0.06
  limit_deg_min: 10
  limit_deg_max: 170
  max_step_deg: 2.5

ballistic_demo:
  enabled: true
  gravity_demo_gain: 0.0009
  max_offset_px: 80

logging:
  file: "data/logs/tracker.log"
